{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: torch==2.5.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (2.5.1)\n",
      "Requirement already satisfied: filelock in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (3.13.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (4.11.0)\n",
      "Requirement already satisfied: networkx in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (3.1.4)\n",
      "Requirement already satisfied: fsspec in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (2024.3.1)\n",
      "Requirement already satisfied: setuptools in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (69.5.1)\n",
      "Requirement already satisfied: sympy==1.13.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch==2.5.1) (1.13.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.5.1) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from jinja2->torch==2.5.1) (2.1.3)\n",
      "Collecting numpy==1.23.5\n",
      "  Downloading numpy-1.23.5.tar.gz (10.7 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.7/10.7 MB\u001b[0m \u001b[31m12.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m0:01\u001b[0m\n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[33 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 112, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     backend = _build_backend()\n",
      "  \u001b[31m   \u001b[0m               ^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 77, in _build_backend\n",
      "  \u001b[31m   \u001b[0m     obj = import_module(mod_path)\n",
      "  \u001b[31m   \u001b[0m           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/Users/zihanzhao/Documents/anaconda3/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "  \u001b[31m   \u001b[0m     return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 1310, in _find_and_load_unlocked\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  \u001b[31m   \u001b[0m   File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/s5/gzgpx4yd20bccw30dhctwcp40000gn/T/pip-build-env-hhsyrz_g/overlay/lib/python3.12/site-packages/setuptools/__init__.py\", line 16, in <module>\n",
      "  \u001b[31m   \u001b[0m     import setuptools.version\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/s5/gzgpx4yd20bccw30dhctwcp40000gn/T/pip-build-env-hhsyrz_g/overlay/lib/python3.12/site-packages/setuptools/version.py\", line 1, in <module>\n",
      "  \u001b[31m   \u001b[0m     import pkg_resources\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/s5/gzgpx4yd20bccw30dhctwcp40000gn/T/pip-build-env-hhsyrz_g/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py\", line 2172, in <module>\n",
      "  \u001b[31m   \u001b[0m     register_finder(pkgutil.ImpImporter, find_on_path)\n",
      "  \u001b[31m   \u001b[0m                     ^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "\u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "Collecting huggingface-hub==0.28.1\n",
      "  Downloading huggingface_hub-0.28.1-py3-none-any.whl.metadata (13 kB)\n",
      "Requirement already satisfied: filelock in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (2024.3.1)\n",
      "Requirement already satisfied: packaging>=20.9 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (6.0.1)\n",
      "Requirement already satisfied: requests in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (2.32.2)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (4.66.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub==0.28.1) (4.11.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub==0.28.1) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub==0.28.1) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub==0.28.1) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub==0.28.1) (2024.12.14)\n",
      "Downloading huggingface_hub-0.28.1-py3-none-any.whl (464 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m464.1/464.1 kB\u001b[0m \u001b[31m9.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: huggingface-hub\n",
      "  Attempting uninstall: huggingface-hub\n",
      "    Found existing installation: huggingface_hub 0.24.6\n",
      "    Uninstalling huggingface_hub-0.24.6:\n",
      "      Successfully uninstalled huggingface_hub-0.24.6\n",
      "Successfully installed huggingface-hub-0.28.1\n",
      "Collecting transformers==4.48.2\n",
      "  Downloading transformers-4.48.2-py3-none-any.whl.metadata (44 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.4/44.4 kB\u001b[0m \u001b[31m4.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: filelock in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (3.13.1)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (0.28.1)\n",
      "Requirement already satisfied: numpy>=1.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (6.0.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (2023.10.3)\n",
      "Requirement already satisfied: requests in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (2.32.2)\n",
      "Collecting tokenizers<0.22,>=0.21 (from transformers==4.48.2)\n",
      "  Downloading tokenizers-0.21.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (6.7 kB)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (0.4.5)\n",
      "Requirement already satisfied: tqdm>=4.27 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers==4.48.2) (4.66.4)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.24.0->transformers==4.48.2) (2024.3.1)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.24.0->transformers==4.48.2) (4.11.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->transformers==4.48.2) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->transformers==4.48.2) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->transformers==4.48.2) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->transformers==4.48.2) (2024.12.14)\n",
      "Downloading transformers-4.48.2-py3-none-any.whl (9.7 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.7/9.7 MB\u001b[0m \u001b[31m14.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hDownloading tokenizers-0.21.0-cp39-abi3-macosx_11_0_arm64.whl (2.6 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.6/2.6 MB\u001b[0m \u001b[31m10.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: tokenizers, transformers\n",
      "  Attempting uninstall: tokenizers\n",
      "    Found existing installation: tokenizers 0.19.1\n",
      "    Uninstalling tokenizers-0.19.1:\n",
      "      Successfully uninstalled tokenizers-0.19.1\n",
      "  Attempting uninstall: transformers\n",
      "    Found existing installation: transformers 4.44.2\n",
      "    Uninstalling transformers-4.44.2:\n",
      "      Successfully uninstalled transformers-4.44.2\n",
      "Successfully installed tokenizers-0.21.0 transformers-4.48.2\n",
      "Collecting datasets==3.2.0\n",
      "  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)\n",
      "Requirement already satisfied: filelock in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (3.13.1)\n",
      "Requirement already satisfied: numpy>=1.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (1.26.4)\n",
      "Collecting pyarrow>=15.0.0 (from datasets==3.2.0)\n",
      "  Downloading pyarrow-19.0.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (3.3 kB)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (0.3.8)\n",
      "Requirement already satisfied: pandas in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (2.2.2)\n",
      "Requirement already satisfied: requests>=2.32.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (2.32.2)\n",
      "Requirement already satisfied: tqdm>=4.66.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (4.66.4)\n",
      "Requirement already satisfied: xxhash in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (2.0.2)\n",
      "Requirement already satisfied: multiprocess<0.70.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (0.70.15)\n",
      "Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets==3.2.0) (2024.3.1)\n",
      "Requirement already satisfied: aiohttp in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (3.9.5)\n",
      "Requirement already satisfied: huggingface-hub>=0.23.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (0.28.1)\n",
      "Requirement already satisfied: packaging in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (23.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets==3.2.0) (6.0.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets==3.2.0) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets==3.2.0) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets==3.2.0) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets==3.2.0) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets==3.2.0) (1.9.3)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.23.0->datasets==3.2.0) (4.11.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.2.0) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.2.0) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.2.0) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets==3.2.0) (2024.12.14)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas->datasets==3.2.0) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas->datasets==3.2.0) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas->datasets==3.2.0) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.2.0) (1.16.0)\n",
      "Downloading datasets-3.2.0-py3-none-any.whl (480 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m480.6/480.6 kB\u001b[0m \u001b[31m2.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading pyarrow-19.0.0-cp312-cp312-macosx_12_0_arm64.whl (30.7 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m30.7/30.7 MB\u001b[0m \u001b[31m9.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: pyarrow, datasets\n",
      "  Attempting uninstall: pyarrow\n",
      "    Found existing installation: pyarrow 14.0.2\n",
      "    Uninstalling pyarrow-14.0.2:\n",
      "      Successfully uninstalled pyarrow-14.0.2\n",
      "  Attempting uninstall: datasets\n",
      "    Found existing installation: datasets 2.19.1\n",
      "    Uninstalling datasets-2.19.1:\n",
      "      Successfully uninstalled datasets-2.19.1\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "streamlit 1.32.0 requires protobuf<5,>=3.20, but you have protobuf 5.29.3 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed datasets-3.2.0 pyarrow-19.0.0\n",
      "Collecting peft==0.14.0\n",
      "  Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)\n",
      "Requirement already satisfied: numpy>=1.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (23.2)\n",
      "Requirement already satisfied: psutil in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (5.9.0)\n",
      "Requirement already satisfied: pyyaml in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (6.0.1)\n",
      "Requirement already satisfied: torch>=1.13.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (2.5.1)\n",
      "Requirement already satisfied: transformers in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (4.48.2)\n",
      "Requirement already satisfied: tqdm in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (4.66.4)\n",
      "Collecting accelerate>=0.21.0 (from peft==0.14.0)\n",
      "  Downloading accelerate-1.3.0-py3-none-any.whl.metadata (19 kB)\n",
      "Requirement already satisfied: safetensors in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (0.4.5)\n",
      "Requirement already satisfied: huggingface-hub>=0.25.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from peft==0.14.0) (0.28.1)\n",
      "Requirement already satisfied: filelock in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->peft==0.14.0) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->peft==0.14.0) (2024.3.1)\n",
      "Requirement already satisfied: requests in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->peft==0.14.0) (2.32.2)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->peft==0.14.0) (4.11.0)\n",
      "Requirement already satisfied: networkx in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.14.0) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.14.0) (3.1.4)\n",
      "Requirement already satisfied: setuptools in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.14.0) (69.5.1)\n",
      "Requirement already satisfied: sympy==1.13.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.14.0) (1.13.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.13.0->peft==0.14.0) (1.3.0)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers->peft==0.14.0) (2023.10.3)\n",
      "Requirement already satisfied: tokenizers<0.22,>=0.21 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers->peft==0.14.0) (0.21.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.13.0->peft==0.14.0) (2.1.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->peft==0.14.0) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->peft==0.14.0) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->peft==0.14.0) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->peft==0.14.0) (2024.12.14)\n",
      "Downloading peft-0.14.0-py3-none-any.whl (374 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m374.8/374.8 kB\u001b[0m \u001b[31m12.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading accelerate-1.3.0-py3-none-any.whl (336 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m336.6/336.6 kB\u001b[0m \u001b[31m18.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: accelerate, peft\n",
      "Successfully installed accelerate-1.3.0 peft-0.14.0\n",
      "Requirement already satisfied: pandas==2.2.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (2.2.2)\n",
      "Requirement already satisfied: numpy>=1.26.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas==2.2.2) (1.26.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas==2.2.2) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas==2.2.2) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas==2.2.2) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.16.0)\n",
      "Collecting trl==0.14.0\n",
      "  Downloading trl-0.14.0-py3-none-any.whl.metadata (12 kB)\n",
      "Requirement already satisfied: accelerate>=0.34.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from trl==0.14.0) (1.3.0)\n",
      "Requirement already satisfied: datasets>=2.21.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from trl==0.14.0) (3.2.0)\n",
      "Requirement already satisfied: rich in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from trl==0.14.0) (13.3.5)\n",
      "Requirement already satisfied: transformers>=4.46.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from trl==0.14.0) (4.48.2)\n",
      "Requirement already satisfied: numpy<3.0.0,>=1.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (23.2)\n",
      "Requirement already satisfied: psutil in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (5.9.0)\n",
      "Requirement already satisfied: pyyaml in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (6.0.1)\n",
      "Requirement already satisfied: torch>=2.0.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (2.5.1)\n",
      "Requirement already satisfied: huggingface-hub>=0.21.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (0.28.1)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from accelerate>=0.34.0->trl==0.14.0) (0.4.5)\n",
      "Requirement already satisfied: filelock in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (3.13.1)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (19.0.0)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (0.3.8)\n",
      "Requirement already satisfied: pandas in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (2.2.2)\n",
      "Requirement already satisfied: requests>=2.32.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (2.32.2)\n",
      "Requirement already satisfied: tqdm>=4.66.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (4.66.4)\n",
      "Requirement already satisfied: xxhash in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (2.0.2)\n",
      "Requirement already satisfied: multiprocess<0.70.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (0.70.15)\n",
      "Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (2024.3.1)\n",
      "Requirement already satisfied: aiohttp in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from datasets>=2.21.0->trl==0.14.0) (3.9.5)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers>=4.46.0->trl==0.14.0) (2023.10.3)\n",
      "Requirement already satisfied: tokenizers<0.22,>=0.21 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from transformers>=4.46.0->trl==0.14.0) (0.21.0)\n",
      "Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from rich->trl==0.14.0) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from rich->trl==0.14.0) (2.15.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets>=2.21.0->trl==0.14.0) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets>=2.21.0->trl==0.14.0) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets>=2.21.0->trl==0.14.0) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets>=2.21.0->trl==0.14.0) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from aiohttp->datasets>=2.21.0->trl==0.14.0) (1.9.3)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.21.0->accelerate>=0.34.0->trl==0.14.0) (4.11.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->trl==0.14.0) (0.1.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (2024.12.14)\n",
      "Requirement already satisfied: networkx in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (3.1.4)\n",
      "Requirement already satisfied: setuptools in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (69.5.1)\n",
      "Requirement already satisfied: sympy==1.13.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (1.13.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from sympy==1.13.1->torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (1.3.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas->datasets>=2.21.0->trl==0.14.0) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas->datasets>=2.21.0->trl==0.14.0) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from pandas->datasets>=2.21.0->trl==0.14.0) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.21.0->trl==0.14.0) (1.16.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/zihanzhao/Documents/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (2.1.3)\n",
      "Downloading trl-0.14.0-py3-none-any.whl (313 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m313.9/313.9 kB\u001b[0m \u001b[31m3.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: trl\n",
      "Successfully installed trl-0.14.0\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement bitsandbytes==0.45.1 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[31mERROR: No matching distribution found for bitsandbytes==0.45.1\u001b[0m\u001b[31m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install torch==2.5.1 -U\n",
    "!pip install numpy==1.23.5 -U\n",
    "!pip install huggingface-hub==0.28.1 -U\n",
    "!pip install transformers==4.48.2 -U\n",
    "!pip install datasets==3.2.0 -U\n",
    "!pip install peft==0.14.0 -U\n",
    "!pip install pandas==2.2.2 -U\n",
    "!pip install trl==0.14.0 -U \n",
    "!pip install bitsandbytes==0.45.1 -U\n",
    "\n",
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## This notebook can be completed on Colab. You will need a GPU to train the model. Export this notebook to colab and run the cell above this to install the necessary packages. Be sure to use a T4 GPU runtime. Also upload your train.csv, training_utils.py, and submission.py files to Colab, in the same directory as this notebook. To verify you have saved the files in the correct place, you should be able to run the import cells below with no import errors, after the packages above have been installed."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Part 0: Following up from the previous assignment...\n",
    "\n",
    "In the previous assignment, you had to prompt engineer Gemini 1.5 to perform arithmetic. \n",
    "\n",
    "It was not an entirely trivial task, despite Gemini 1.5 being a large language model, probably trained on text that explains how to do arithmetic.\n",
    "\n",
    "In particular, Gemini struggled with large number arithmetic because there are not many of such examples on the internet, when compared to small number arithmetic.\n",
    "\n",
    "Small language models are even worse at arithmetic, but you can fine tune them to use tools like a user-defined calculator.\n",
    "\n",
    "In this assignment, you will train a small language model to use a simple calculator that you will build. \n",
    "\n",
    "## To Do:\n",
    "\n",
    "1. Implement the `prepare_data()`, `use_calculator()`, `api_key()`, and `hub_model_name()` functions in `submission.py`\n",
    "2. Read the code below and read `training_utils.py`. Take time to understand how the code works. The provided code contains the functions that are needed to perform instruction fine tuning, which does not follow the exact same process as the auto-regressive, next token prediction fine tuning method. While you will not be graded on whether you read the code, you should try to understand it for your own education.\n",
    "3. Fill out the lines in `training_utils.py` that are commented with `TODO`. These are hyperparameters you need to tune. You are free to tune any of the hyperparameters, but you should be able to get a good model with just the TODO hyperparameters.\n",
    "4. Run the code below to train your model. \n",
    "5. Push your model to the Hugging Face Hub with the `hub_model_name()` function. This should be in the final cell of this notebook.\n",
    "\n",
    "Thus, this notebook is where you can test the model and push it to the hub but you will not be graded on this notebook. Your `submission.py` file will contain the code used to create the data set and your huggingface information, which we will use to pull your model for grading. `training_utils.py` contains the code used to train the model with hyperparameters you can tune to facillitate your training, but you will **not** be graded on that file either."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'peft'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtraining_utils\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mtraining_utils\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01msubmission\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01msubmission\u001b[39;00m\n",
      "File \u001b[0;32m~/Documents/2025 Winter Quater/360/HW/stat360-hw3/training_utils.py:5\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtransformers\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m AutoModelForCausalLM, AutoTokenizer, TrainingArguments \n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdatasets\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Dataset\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpeft\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m PeftModel, LoraConfig, get_peft_model\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtrl\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m SFTTrainer, DataCollatorForCompletionOnlyLM\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'peft'"
     ]
    }
   ],
   "source": [
    "import training_utils as training_utils\n",
    "import submission as submission"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### The following cell can be run after you implement part TODO 1,2 and 3 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sft_config = training_utils.SFTConfig\n",
    "sft_config.hf_key = submission.api_key()\n",
    "model, tokenizer = training_utils.load_model(sft_config)\n",
    "df = submission.prepare_data('train.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### The following cell runs TODO part 4\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "trained_model = training_utils.train(dataset=df, config=sft_config)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Part 1: Testing your model\n",
    "\n",
    "The code below tests your model. It should do well on the training set since this is what you trained on.\n",
    "\n",
    "###  Grading Criteria:\n",
    "\n",
    "Accuracy is define as the proportion of correct answers.\n",
    "\n",
    "Your grade will be assigned based on the accuracy of your model.\n",
    "\n",
    "Because you are training the model to use a calculator only, the accuracy should be very close to 1.0, if not at 1.0, thus the grading criteria will have a higher bar for accuracy.\n",
    "\n",
    "On the evaluation set, your assignment score will be calculated as follows:\n",
    "\n",
    "- Accuracy >= 1.0: 1 * Full points\n",
    "- Accuracy >= 0.98: 0.95 * Full points\n",
    "- Accuracy >= 0.95: 0.9 * Full points\n",
    "- Accuracy >= 0.9: 0.8 * Full points\n",
    "- Accuracy >= 0.85: 0.75 * Full points\n",
    "- Accuracy >= 0.5: 0.7 * Full points\n",
    "- Else: 0.5 * Full points\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "test_df = pd.read_csv('train.csv')\n",
    "operations = {'add': '+', 'subtract': '-', 'multiply': '*'}\n",
    "correct = 0\n",
    "running_total = 0\n",
    "for k, r in test_df.iterrows():\n",
    "    running_total += 1\n",
    "    response = training_utils.run_inference_with_model(trained_model, tokenizer, f'### Question: What is {r[\"num1\"]} {operations[r[\"operation\"]]} {r[\"num2\"]}?\\n ### Answer:', config=sft_config)\n",
    "    try:\n",
    "        if submission.capture_output(response) == r['result']:\n",
    "            correct += 1\n",
    "        print(f'{r[\"num1\"]} {operations[r[\"operation\"]]} {r[\"num2\"]} = ', submission.capture_output(response), 'compare with ', r['result'], 'score: ', f\"{correct}/{running_total}\")\n",
    "    except:\n",
    "        print(response, 'UNABLE TO GET TOOL USE')\n",
    "print(f'Accuracy: {correct/len(test_df)}')\n",
    "\n",
    "response = training_utils.run_inference(sft_config, '### Question: What is 651475 * 4458?\\n ### Answer:')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "If you are struggingly to get the full accuracy, you might want to train your model on more data, or on more diverse data. \n",
    "\n",
    "Many methods in machine learning exist to improve the accuracy of your model, in particular such as data augmentation to encourage regularization and prevent overfitting.\n",
    "\n",
    "Your model might learn a spurious correlation, e.g. it may be most subtraction problems begin with a number starting with a 9, so any time it sees a number starting with a 9, it will assign it a subtraction operation. To prevent this type of overfitting, you can add data to your training set that does not have this pattern. This is just an example and may not hold true for your model, but you should observe what patterns your model is learning, why it is learning them, and how can you encourage it to learn other patterns.\n",
    "\n",
    "This means you might want to append more examples to `train.csv` to encourage your model to learn other patterns. If you choose to do this, take a look at the `train.csv` file and add new entries to the file, following the same format as the rest of the entries in the data set. You should be able to write some code to do this systematically. Keep in mind the larger the data set, the more memory and time it will take to train the model. You may also delete some of the training data if you think it is not useful for training the model.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Part 2: Push your model to the Hugging Face Hub\n",
    "\n",
    "When you are satisfied with your model, you will push your model to the Hugging Face Hub by giving it a name and using your API key.\n",
    "\n",
    "The name should be in the format of `<username>/<model name>` without the brackets.\n",
    "\n",
    "For example if your username is `johndoe` and you want the model name to be `sft-calculator`, the name should be `johndoe/sft-calculator`.  \n",
    "\n",
    "This completes TODO part 5."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "trained_model.push_to_hub(submission.hub_model_name(), token=submission.api_key())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
